version: '3'

services:
  landing-page-app:
    image: landing-page
    build: .
    ports:
      - 3000:3000
  landing-page-fallback:
    image: landing-page-fallback
    build: fallback-page
    ports:
      - 3000:3001
