import './globals.css'
import { Sono, Inter, Josefin_Slab, Poppins, Maven_Pro } from 'next/font/google'
import { MenuContextWrapper } from './MenuContextWrapper'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--inter-font',
  display: 'swap'
})

const sono = Sono({
  subsets: ['latin'],
  variable: '--sono-font',
  display: 'swap'
})

const josefinSlab = Josefin_Slab({
  subsets: ['latin'],
  variable: '--josefin-slab-font',
  display: 'swap'
})

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--poppins-font',
  display: 'swap'
})

const mavenPro = Maven_Pro({
  subsets: ['latin'],
  variable: '--maven-pro-font'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${mavenPro.variable} ${sono.variable} ${inter.variable} ${josefinSlab.variable} ${poppins.variable}`}
    >
      <body className="antialiased bg-slate-50">
        <MenuContextWrapper>{children}</MenuContextWrapper>
      </body>
    </html>
  )
}
